name: Update Flathub Package
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout flathub repo
        uses: actions/checkout@v4
      - name: Update Manifest
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download -p "com.saunasim.saunasim.yml" --clobber
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7